project:
  type: manuscript

manuscript:
  article: tidy-questionnaire-paper.qmd

format:
  scientific-data-pdf: default
#format:
#  html:
#    comments:
#      hypothesis: true
#  docx: default
#  jats: default

  # (other formats)
  # pdf: default

# execute:
#   freeze: true



