project:
  type: manuscript
  render:
    - "*.qmd"
    - "R/*.qmd"

manuscript:
  article: tidy-questionnaire-paper.qmd

format:
  scientific-data-pdf: default

notebook-links: false
execute:
  echo: fenced
  eval: false




